name: Cypress Tests by Priyam

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Edit watcher
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - run: npm ci
      - run: npm run start:ci:windows & npx wait-on http://localhost:8080

      - name: Install Browserstack 
        run: sudo npm install -g browserstack-cypress-cli
      
      - name: BrowserStack Test
        env:
          BROWSERSTACK_USERNAME: laxmidubey_AtuxlS
          BROWSERSTACK_ACCESS_KEY: j27cANeYvcQW5fUy55pS
        run : |
          browserstack-cypress run --sync
              
