name: Cypress Tests by Priyam

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Edit watcher
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        
        - run: npm ci
        - run: sudo npm i -g pm2
        - run: npm run build
        - run: npm start
        - run : sudo npm install -g browserstack-cypress-cli
      
      - name: BrowserStack Test
        env:
          BROWSERSTACK_USERNAME: laxmidubey_PYrLpm
          BROWSERSTACK_ACCESS_KEY: 8mq5pvphujadbFMJbJhF
        run : |
          browserstack-cypress run --sync
              
